### ISSUE TITLE
Timestamps on listed files

### ISSUE THREAD

**Issue by stevebanik-ndsc** [daticahealth/cli#32]
It would be nice to see a timestamp on the files that are returned when I run `datica files list service_proxy`.

**Comment by jault3** [comment]
Hey @stevebanik-ndsc , thanks submitting an issue! Would you like to see the last updated timestamp for the file? Or the creation timestamp? Or both/another timestamp?

**Comment by stevebanik-ndsc** [comment]
Hi Josh, I think creation and last updated would be useful.

Thanks!

Steve

**Comment by bartelsb** [comment]
Hi @stevebanik-ndsc ! I apologize for the long delay on our response to this. The latest release of our CLI does allow you to see created at and last updated at timestamps for service files. You can see these timestamps by adding the `-t` flag at the end of your list command. Using the example you provided above, the command would look like this: `datica files list service_proxy -t`. Please let us know if you have any questions or feedback!
