### ISSUE TITLE
Downloading a DB backup returns an error

### ISSUE THREAD

**Issue by marko89kv** [daticahealth/cli#86]
Using version 4.2.5 64-bit on MacOS;

datica db export db_service_container ./db.sql

results in [fatal] strconv.Atoi: parsing "": invalid syntax

datica db download... is erroring out the same, as well.

**Comment by forana** [comment]
Thanks @marko89kv - sorry for the radio silence on this issue. This is an error in the error-reporting flow for `db export`, which shares a fair amount of logic with the `db download` flow. I hope you contacted Datica Support to resolve your issue - if not, please get in touch at https://help.datica.com/
